pre_filefilter: ['- python-cellcutoff', '+ *']

linters:
# Disable cppcheck for now because it does not work on OSX
# See https://github.com/conda-forge/cppcheck-feedstock/pull/8
#  - cppcheck:
  - cpplint:
      script: cpplint
  - doxygen:
  - header:
  - header:
      filefilter: ['+ *.cpp', '+ *.h', '+ *.h.in']
      comment: '// '
      shebang:
      extra: []
  - whitespace:
