pre_filefilter: ['- python-cellcutoff', '+ *']

linters:
  - cppcheck:
  - cpplint:
      filter: '-build/include_order,-runtime/int'
  - doxygen:
  - header:
  - header:
      filefilter: ['+ *.cpp', '+ *.h', '+ *.h.in']
      comment: '// '
      shebang:
      extra: []
  - whitespace:
