project:
  name: cellcutoff
  packages:
    - dist_name: cellcutoff
      tools:
        - write-cmake-version
        - cardboardlint-static
        - cardboardlint-dynamic
        - build-cmake-inplace
        - maketest
        - upload-codecov
        - build-cmake-source
        - build-conda
        - deploy-conda
        - deploy-github
    - dist_name: python-cellcutoff
      path: python-cellcutoff
      tools:
        - write-py-version
        - cardboardlint-static
        - cardboardlint-dynamic
        - build-py-inplace
        - pytest
        - upload-codecov
        - build-py-source
        - build-conda
        - deploy-conda
        - deploy-github
