env:
  matrix:
  - MYCONDAPY=2.7
  #- MYCONDAPY=3.5
  #- MYCONDAPY=3.6
  global:
    - CPPPKG=cellcutoff
    - PYPKG=python-cellcutoff
    - GITHUB_REPO_NAME=theochem/cellcutoff

# Do not use Travis Python to save some time.
language: generic
os:
  - linux
#  - osx
osx_image: xcode6.4
dist: trusty
sudo: false

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+(\.[0-9]+)?([ab][0-9]+)?$/


install:
# Get miniconda. Take the right version, so re-installing python is only needed for 3.5.
- if [[ "$MYCONDAPY" == "2.7" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  else
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- source $HOME/miniconda/bin/activate
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes
- conda update -q conda
# Get the right python version for building. This only does something for 3.5.
# Install extra package needed to make things work. Most things can be listed as
# dependencies on metal.yaml and setup.py, unless setup.py already imports them.
# Install conda tools for packaging and uploading
- conda install python=${MYCONDAPY} numpy cython conda-build anaconda-client
# Install more recent stuff with pip
- pip install codecov coverage
# Show conda info for debugging
- conda info -a

script:
# Make a debug build in-place, for testing with coverage
- (mkdir debug;
  cd debug;
  cmake cmake -DCMAKE_BUILD_TYPE=debug ..;
  make;
  ./cellcutoff/tests/test_cellcutoff)

# Build the conda package
- git fetch origin --tags
- conda build -q tools/conda.recipe

## Build source package, should work too and needed for deployment to Github and
## PyPI.
#- python setup.py sdist

# Install Conda package
- conda install --use-local $CPPPKG

# Run the tests
- ${CONDA_PREFIX}/libexec/${CPPPKG}/test_${CPPPKG}

## Run tests out of source tree, to make sure that installed version is tested.
#- (cd; nosetests $PYPKG -v --detailed-errors --with-coverage --cover-package=$PYPKG --#cover-tests --cover-erase --cover-inclusive --cover-branches --cover-xml)

#after_success:
# Upload the coverage analysis
- codecov
