package:
  name: python-cellcutoff
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
  number: 0
  string: py{{ CONDA_PY }}_0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - cython >=0.24.1
    - cellcutoff
    - setuptools
    - nose
    - gcc
  run:
    - cellcutoff
    - python
    - numpy
    - nose
    - libgcc

about:
  description: Reall-space cutoff library (python wrapper)
  home: https://github.com/theochem/cellcutoff
  license: GPL3
  license_file: LICENSE.txt
  summary: CellCutoff is a library for periodic boundary conditions and real-space cutoff calculations.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
