package:
  name: python-cellcutoff
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  number: 0
  string: py{{ CONDA_PY }}_1
  script_env:
    # Needed to let conda-build pick up the correct SDK on OSX.
    - SDKROOT  # [osx]
  script:
    - python setup.py build_ext -I {{ PREFIX }}/include
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - cython >=0.28.0
    - setuptools
    - numpy
    - cellcutoff =={{ PROJECT_VERSION }}
  run:
    - cellcutoff
    - python
    - numpy

test:
  requires:
    - python
    - pytest
    - pytest-xdist
  commands:
    - conda inspect linkages python-cellcutoff
    - pytest --pyargs cellcutoff -n auto

about:
  description: Periodic boundary conditions and real-space cutoff calculations (Python wrapper)
  home: https://github.com/theochem/cellcutoff
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: CellCutoff is a library for periodic boundary conditions and real-space cutoff calculations.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
