package:
  name: cellcutoff
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  number: 0
  string: 0
  script_env:
    # Needed to let conda-build pick up the correct SDK on OSX.
    - SDKROOT  # [osx]

requirements:
  build:
    - cmake
    - doxygen
    - graphviz
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}

test:
  commands:
    - conda inspect linkages cellcutoff
    - ${PREFIX}/libexec/cellcutoff/test_cellcutoff

about:
  description: Periodic boundary conditions and real-space cutoff calculations
  home: https://github.com/theochem/cellcutoff
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: CellCutoff is a library for periodic boundary conditions and real-space cutoff calculations.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
