package:
  name: cellcutoff
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
  number: 0
  string: 0

requirements:
  build:
    - cmake
    - {{ compiler("cxx") }}

about:
  description: Real-space cutoff library (python wrapper)
  home: https://github.com/theochem/cellcutoff
  license: GPL3
  license_file: LICENSE.txt
  summary: CellCutoff is a library for periodic boundary conditions and real-space cutoff calculations.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
