package:
  name: cellcutoff
  version: "{{ PROJECT_VERSION }}"

source:
  path: ../../

build:
  number: 0
  string: 0
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - >-
      cmake ..
      -DCMAKE_INSTALL_PREFIX=${PREFIX}
      -DCMAKE_BUILD_TYPE=release
      -DCMAKE_OSX_SYSROOT=${CONDA_BUILD_SYSROOT}  # [osx]
    - VERBOSE=1 make install -j ${CPU_COUNT}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - make
    - cmake
    - doxygen
    - graphviz

test:
  commands:
    - conda inspect linkages cellcutoff
    - ${PREFIX}/libexec/cellcutoff/test_cellcutoff

about:
  description: Periodic boundary conditions and real-space cutoff calculations
  home: https://github.com/theochem/cellcutoff
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: CellCutoff is a library for periodic boundary conditions and real-space cutoff calculations.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
