package:
  name: cellcutoff
  version: {{ CELLCUTOFF_VERSION }}

source:
  path: ../../

build:
  script_env:
   - CELLCUTOFF_VERSION
  number: 0
  string: py{{ CONDA_PY }}_0

requirements:
  build:
    - cmake
    - gcc
  run:
    - libgcc

about:
  description: Reall-space cutoff library (python wrapper)
  home: https://github.com/theochem/cellcutoff
  license: GPL3
  license_file: LICENSE.txt
  summary: CellCutoff is a library for periodic boundary conditions and real-space cutoff calculations.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
