package:
  name: cellcutoff
  version: 0.0.0

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - cmake
    - gcc     # [linux]
  run:
    - libgcc  # [linux]

about:
  description: Reall-space cutoff library (python wrapper)
  home: https://github.com/theochem/cellcutoff
  license: GPL3
  license_file: LICENSE.txt
  summary: CellCutoff is a library for periodic boundary conditions and real-space cutoff calculations.

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
